APP_NAME=The-Program
APP_ENV=local
APP_KEY=base64:BuhnwdfS/t2jTJsgPATDiM5hL9Syrw2vLLStEvFGK3Y=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=188.121.57.3
DB_PORT=3306
DB_DATABASE=store
DB_USERNAME=lawyeradmin
DB_PASSWORD=lawyeradmin

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.googlemail.com
MAIL_PORT=465
MAIL_USERNAME=smta55@gmail.com
MAIL_PASSWORD=Ali4309131
MAIL_ENCRYPTION=ssl
MAIL_FROM_ADDRESS=hello@example.com

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
